services:
  planner:
    image: cydoniast/planner:latest
    environment:
      SPRING_RABBITMQ_HOST: 192.168.18.58
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      WINDSERVICE_HOST: 192.168.18.219
      WINDSERVICE_PORT: 8084
      GEOSERVICE_HOST: 192.168.18.219
      GEOSERVICE_PORT: 8082
    command: ["./wait-for-it.sh", "192.168.18.219:9096", "192.168.18.219:9098", "--", "java", "-jar", "eolopark-0.0.1-SNAPSHOT.jar"]
    networks:
      - webapp06_default

networks:
  webapp06_default:
    external: true