services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    ports:
      - '3308:3306'

  broker:
    image: rabbitmq:3.13-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 5
    ports:
      - "5672:5672"

  server:
    image: cydoniast/server:latest
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_HOST: broker
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SERVER_PORT: 443
      SERVER_ENABLED: true
    ports:
      - "443:443"
    networks:
      - webapp06_default

networks:
  webapp06_default:
    external:
      name: webapp06_default

  